apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana-demo
  name: grafana-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-demo
  template:
    metadata:
      labels:
        app: grafana-demo
    spec:
      containers:
      - image: ghcr.io/grischdian/grafana-demo-metrics:v0.0.4
        imagePullPolicy: IfNotPresent
        name: grafana-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana-demo2
  name: grafana-demo2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-demo2
  template:
    metadata:
      labels:
        app: grafana-demo2
    spec:
      containers:
      - image: ghcr.io/grischdian/grafana-demo-metrics:v0.0.4
        command:
        - /metrics-server2
        imagePullPolicy: IfNotPresent
        name: grafana-demo2
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana-demo
  name: grafana-demo
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: web
  selector:
    app: grafana-demo
  type: ClusterIP

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: grafana-demo-monitor
  name: grafana-demo-monitor
spec:
  endpoints:
  - interval: 30s
    port: web
    scheme: http
  selector:
    matchLabels:
      app: grafana-demo

--- 
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: example-alert
spec:
  groups:
  - name: example
    rules:
    - alert: VersionAlert
      expr: b1_cpu_usage > 50


---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana-demo2
  name: grafana-demo2
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: web
  selector:
    app: grafana-demo2
  type: ClusterIP

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: grafana-demo-monitor2
  name: grafana-demo-monitor2
spec:
  endpoints:
  - interval: 30s
    port: web
    scheme: http
  selector:
    matchLabels:
      app: grafana-demo2

---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: example-app
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: example-app
  podMetricsEndpoints:
  - port: web
---
